[general]
context=default
allowoverlap=no
udpbindaddr=0.0.0.0
transport=udp
srvlookup=yes
disallow=all
allow=ulaw
allow=alaw

[softphone]
type=friend
secret=gastrovoice123
host=dynamic
context=gastrovoice
dtmfmode=rfc2833
canreinvite=no
